### ISSUE TITLE
Browsing DiskStation DLNA server throws errors

### ISSUE THREAD

**Issue by hadess** [phako/dleyna-server#5]
Using rhythmbox from Flathub, I get those warnings using the grilo DLNA source. Could those warnings be made quiet?

```
(rhythmbox:2): Grilo-WARNING **: 11:02:39.504: [dleyna] ../src/dleyna/grl-dleyna-source.c:765: grl_dleyna_source_results error:GDBus.Error:com.intel.dleyna.OperationFailed: Unable to parse results of browse: Empty 'DIDL-Lite' node in the DIDL-Lite XML:
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:sec="http://www.sec.co.kr/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/"></DIDL-Lite>
```

**Comment by phako** [comment]
This might need (additional) changes in gupnp-av, the message is either from there or from libxml2

**Comment by hadess** [comment]
I was expecting to start with dleyna-server not throwing that error, even if it isn't made quiet at the source. It seems to have a separate error code.

**Comment by phako** [comment]
Found it. dleyna-server shouldn't try to parse the DIDL if the numbers returned in those calls is 0; currently it first parses the DIDL unconditionally

**Comment by phako** [comment]
Ah no, I broke that when untangling gupnp-av from gupnp

**Comment by phako** [comment]
https://github.com/phako/dleyna-renderer/commit/92b53e1ba868c717227bdb60e9754ad37dae5cd0 is the fix for dleyna-renderer
