### ISSUE TITLE
 New release for GUPnP 1.6 support?

### ISSUE THREAD

**Issue by mattst88** [phako/dleyna-server#7]
Can we get a release with GUPnP 1.6 support, or is there something more to do?

**Comment by phako** [comment]
see https://gitlab.gnome.org/World/dLeyna/-/issues/7 - https://gitlab.gnome.org/World/dLeyna/-/issues/6 needs a proper fix otherwise there is a high potential for endless loops in server and renderer

**Comment by phako** [comment]
https://gitlab.gnome.org/World/dLeyna/-/releases/v0.8.0
